version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80
    volumes:
      - ./src:/var/www
    links:
      - mysql
    container_name: php

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: appDB
      MYSQL_USER: user 
      MYSQL_PASSWORD: password
    volumes:
      - ./databases:/docker-entrypoint-initdb.d
      - databases:/var/lib/mysql
    container_name: mysql

volumes:
  databases: